# Generated by Django 6.0.2 on 2026-02-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField()),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('number_of_guests', models.PositiveIntegerField()),
                ('group_tour', models.BooleanField(default=False)),
            ],
        ),
    ]
