# Generated by Django 6.0.2 on 2026-02-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='event_id',
            field=models.CharField(unique=True),
        ),
    ]
