# Generated by Django 6.0.2 on 2026-02-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='event_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
