# Generated by Django 5.2.11 on 2026-03-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='guest_name',
            field=models.CharField(default='name goes here'),
            preserve_default=False,
        ),
    ]
