# Generated by Django 5.2.11 on 2026-03-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='guest_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
