# Generated by Django 5.2.11 on 2026-03-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('message_sent', 'Message Sent'), ('confirmed', 'Confirmed'), ('past_event', 'Past Event')], default='unassigned', max_length=20),
        ),
    ]
