# Generated by Django 5.2.11 on 2026-03-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
