# Generated by Django 5.2.11 on 2026-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('message_sent', 'Message Sent'), ('confirmed', 'Confirmed'), ('past_event', 'Past Event'), ('cancelled', 'Tour Cancelled')], default='unassigned', max_length=20),
        ),
    ]
