# Generated by Django 5.2.11 on 2026-04-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_migrate_guest_name_to_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('number_of_guests', models.PositiveIntegerField()),
                ('group_tour', models.BooleanField(default=False)),
                ('guest_name', models.CharField()),
                ('week_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
