# Generated by Django 5.2.11 on 2026-04-05 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='past_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='tour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour'),
        ),
    ]
