# Generated by Django 5.2.11 on 2026-05-29 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_guest_past_event_guest_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='tour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
    ]
