# Generated by Django 5.2.11 on 2026-06-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_guest_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='cell_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='guest',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='guest',
            name='major_of_interest',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='guest',
            name='purpose_of_visit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='guest',
            name='questions_comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
