# Generated by Django 5.2.11 on 2026-06-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_guest_cell_number_guest_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='ambassador',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
